### PR TITLE
Parameterize chunk.py

### PR DESCRIPTION
**Pull request by kdeloach**
Replaces single JSON file with command line arguments to make it
easier to create a cluster with different options. The SQS queue name
and output file path have also been parameterized.

Connects #4

Depends on #8

### CODE REVIEW

**Comment by kdeloach** [comment]
Needs to be rebased once #1 is merged.

**Comment by hectcastro** [comment]
Just a heads up that #1 was merged.

**Comment by kdeloach** [comment]
Thanks, rebased.

**Comment by kdeloach** [comment]
I'm troubleshooting pyspark errors now.

**Comment by kdeloach** [comment]
I have tested and verified that this works on EMR.

**Comment by echeipesh** [comment]
+1

**Pull request merged**
